### ISSUE TITLE
Mapping LocalDateTime

### ISSUE THREAD

**Issue by mvozny** [AnnotationSro/java-annotation-mapper#1]
problem with creating instance in generated mapperImpl:

LocalDateTime out  = new LocalDateTime(); 

... no public constructor

**Comment by slany** [comment]
Hi, thanks for you issue.

Mapper has updated list of immputable types + is added new annotation for configuration own immputable types. New annotation @MapperConfig(immutable = {Obj1.class}) can be defined on Mapper type or package.
Example with test is in  sk.annotation.library.jam.example.ex12.ExampleImmputableMapper.
