### ISSUE TITLE
Field mapping direction

### ISSUE THREAD

**Issue by mvozny** [AnnotationSro/java-annotation-mapper#4]
ignoreDirectionS2D parameter in @FieldMapping annotation is not working properly.
eg.:

`
@Mapper
@EnableSpring
@MapperFieldConfig(
        fieldMapping = {
                @FieldMapping(s = "AccountDTO.id", d = "Account.id", ignoreDirectionS2D = true)
        }
)
public abstract class AccountMapper {
    abstract public Account mapAccountFromDto(AccountDTO accountDTO);
}
`

Code above should generate implementation where "id" is ignored in resulting Account object, but it is still present. (not working even with fully quailifed class names)

**Comment by slany** [comment]
Resolved - look at `sk.annotation.library.jam.example.ex16.CustomFieldMapper`
